CREATE DATABASE TASK01;
USE TASK01;

CREATE TABLE EMPLOYEE
(
EMP_ID INT,
EMP_NAME VARCHAR(50),
EMP_CNIC CHAR(13),
EMP_DOB DATE,
);

INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_CNIC, EMP_DOB)VALUES(001, 'FAHEEM PASHA', '123456789123', '2001-07-23');
INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_CNIC, EMP_DOB)VALUES(002, 'MEHMET', '0987654321123', '1999-06-07');
INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_CNIC, EMP_DOB)VALUES(003, 'CANDARLI', '123456789125', '1990-01-21');
INSERT INTO EMPLOYEE(EMP_ID, EMP_NAME, EMP_CNIC, EMP_DOB)VALUES(004, 'BA YEZID', '123466000123', '2004-12-30');

SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE
SET EMP_NAME = 'MEHMOOD SHAH' WHERE EMP_ID = 1;
SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE
SET EMP_DOB = '1989-04-20' WHERE EMP_ID = 4;
SELECT * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE EMP_ID  = 1;
SELECT * FROM EMPLOYEE;

-- ALTER / CHANGE TABLE STRUCTURE: COLUMNS/ ROWS ETC
ALTER TABLE EMPLOYEE DROP COLUMN EMP_NAME;
SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE ADD  EMP_ROLE VARCHAR(50);
SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET EMP_ROLE = 'MANAGER' WHERE EMP_ID = 2;
SELECT * FROM EMPLOYEE;